### ISSUE TITLE
Problem building latest examples ...

### ISSUE THREAD

**Issue by nmcl** [kenfinnigan/ejm-samples#15]
mvn compile eventually gives ...

[INFO] Chapter 11: Cayambe Admin Service 1.0-SNAPSHOT ..... SKIPPED
[INFO] Chapter 11: Cayambe Kafka Service 1.0-SNAPSHOT ..... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.794 s
[INFO] Finished at: 2020-08-02T16:56:02+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project cayambe: Compilation failure: Compilation failure: 
[ERROR] Source option 1.5 is no longer supported. Use 1.6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
[ERROR] -> [Help 1]

Using maven 3.6.3 and Java 9 on Mac OS 10.14.6

**Comment by nmcl** [comment]
OK I tried this with the same version of maven on Mac OS 10.13.6 (different machine entirely) and java version "1.8.0_66" with no problems at all. I'll check my original build system and try 1.8 there too.

**Comment by nmcl** [comment]
Went back to original machine and replaced Java 9 with 8 and it works fine. Since I didn't change anything else I think this can be written up as a 9 versus 8 issue.

**Comment by kenfinnigan** [comment]
Suspected as much but not sure why I know others have used Java 11 with success.

Will look to update the examples soon

**Comment by kenfinnigan** [comment]
`main` is now requiring JDK 11, so this should be resolved
