### ISSUE TITLE
Stock quote example no longer works out of the box

### ISSUE THREAD

**Issue by nmcl** [kenfinnigan/ejm-samples#16]
In the past (with WildFly Swarm), the Chapter 8 stock client example worked out of the box. Now it seems the quote service it relies upon ("https://sandbox.tradier.com/v1/markets/quotes?symbols=") requires some form of token authorisation for use. If I issue ...

mvn thorntail:run

... in stock-client directory (in chapter8) then try to hit http://localhost:8080/single/AAPL I get "Not Found" returned.

If I go direct to https://sandbox.tradier.com/v1/markets/quotes?symbols=APPL I get a "Invalid access token" returned.

I don't remember having to do something beforehand to use the stock quote example in the past so assume something has changed with the sandbox.tradier.com site.

**Comment by nmcl** [comment]
I should add that I did have a trader.com account and replaced the Bearer access token in the code with my own. I must be missing something though.

**Comment by kenfinnigan** [comment]
Can't seem to login into their site right now, not sure if it's no longer working.

Will investigate more tonight.

I'm working on updating everything to JDK 11 base and latest versions of Thorntail, etc

**Comment by nmcl** [comment]
Try https://www.alphavantage.co/documentation/ ?

**Comment by kenfinnigan** [comment]
Found the fix.

Committed to https://github.com/kenfinnigan/ejm-samples/tree/jdk11-update, it will become `main` branch when I've verified all examples work on JDK 11.

The issue was that Thorntail removed the automatic generation of JAX-RS Application class

**Comment by nmcl** [comment]
Any update on when this might become the main branch?

**Comment by kenfinnigan** [comment]
I haven't manually verified every service yet, but it does compile.

Might make it `main` and fix issues rolling forward

**Comment by kenfinnigan** [comment]
Branches switched
