### ISSUE TITLE
Wonderful Book!

### ISSUE THREAD

**Issue by javabean68** [kenfinnigan/ejm-samples#3]
Hi Ken,

my congratulations on your book and on Thorntail! I find them super! I read your Enterprise Java Microservices on Oreilly Safari and bought it on Amazon.

The examples in this repository are also very interesting. I believe however I'm missing something in chapter 6. In order to avoid a 404 in the Client Applications as I call them in the browser I had to had something like:

`package ejm.jaxrsclient;

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

/**
 * @author Fabio Salvi
 */
@ApplicationPath("/")
public class MainApplication extends Application {
}`

I have a question to you: what do you think of OpenLiberty? My Firma is about to choice a microservice platform and I should with other colleagues of mine report the pros and the cons of the 2..

I'm convinced Thorntail is the best! :-) Do you have any tip to reinforce my opinion? I have been working only with JEE 7 and I am not a Microservice Expert at all...

Thank you very much in advance for your time!
Regards

Fabio

**Comment by kenfinnigan** [comment]
Hi Fabio,

Great to hear you enjoy the book and Thorntail!

With respect to the `@ApplicationPath` being required. If you'd like to submit a PR with the change I can look at it.

There are definitely differences between OpenLiberty and Thorntail. The biggest is that OpenLiberty is a full fledged application server that also offers MicroProfile functionality, whereas Thorntail is geared more towards typical microservice and cloud type deployments.

**Comment by kenfinnigan** [comment]
Thanks for the pull request!
